# Greenhorn config file

homepage = "home"

html_template = "/home/paunstefan/greenhorn_data/templates/template.html"
css = "/home/paunstefan/greenhorn_data/templates/style.css"
list_template = "/home/paunstefan/greenhorn_data/templates/list.html"
media_dir = "/home/paunstefan/greenhorn_data/pages/static"

[[pages]]
name = "home"
kind = "Single"
source = "/home/paunstefan/greenhorn_data/pages/home.md"

[[pages]]
name = "articles"
kind = "List"
source = "/home/paunstefan/greenhorn_data/pages/articles"

[[pages]]
name = "interesting"
kind = "Single"
source = "/home/paunstefan/greenhorn_data/pages/interesting_links.md"

