# Greenhorn config file

homepage = "home"

html_template = "data/templates/template.html"
css = "data/templates/style.css"
list_template = "data/templates/list.html"
media_dir = "data/pages/images"

[[pages]]
name = "home"
kind = "Single"
source = "data/pages/home.md"

[[pages]]
name = "articles"
kind = "List"
source = "data/pages/articles"

[[pages]]
name = "interesting"
kind = "Single"
source = "data/pages/interesting_links.md"
